name: example
description: "An example app using loading_state_handler"
publish_to: "none"
version: 0.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  loading_state_handler:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
