name: example
description: "An example app using loading_state_handler"
publish_to: "none"
version: 0.2.0

environment:
  sdk: ^3.5.4

dependencies:
  loading_state_handler:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
