name: loading_state_handler
description: "The StateHandlerWidget manages different UI states—loading, error, empty, and normal—allowing you to customize the displayed widgets for each state."
version: 1.4.0
homepage: https://github.com/Mahmoud-Saeed-Mahmoud/loading_state_handler

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

false_secrets: 
  - '*.json'
