name: loading_state_handler
description: "A powerful Flutter widget for managing UI states with built-in retry functionality. This widget handles loading, error, empty, and normal states elegantly while providing a customizable retry mechanism with cooldown support."
version: 2.1.0
homepage: https://github.com/Mahmoud-Saeed-Mahmoud/loading_state_handler
documentation: https://mahmoud-saeed-mahmoud.github.io/loading_state_handler
issue_tracker: https://github.com/Mahmoud-Saeed-Mahmoud/loading_state_handler/issues
repository: https://github.com/Mahmoud-Saeed-Mahmoud/loading_state_handler
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - widget
  - state
  - loading
  - error

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
