name: Publish to pub.dev
on:
    workflow_dispatch:
      inputs:
         ref:
           type: string
           description: ref of the tag to be published

jobs:
  publish:
    permissions:
       id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
