name: Publish Package to pub.dev

on:
  workflow_dispatch:
        
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Install Flutter SDK
      uses: subosito/flutter-action@v2
        
    - name: Install dependencies
      run: flutter pub get

    - name: Publish Package
      run: dart pub publish --force
      env:
        PUB_TOKEN: ${{ secrets.PUB_TOKEN }}
        senstive: true
