name: Publish to pub.dev

on:
  workflow_dispatch:
    
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.14.0
        

      - name: Set up pub.dev credentials
        run: |
          mkdir -p ~/.pub-cache
          echo "//pub.dev:$(PUB_DEV_TOKEN)" > ~/.pub-cache/credentials.json
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}

      - name: Publish to pub.dev
        run: dart pub publish --force
        env:
          PUB_CACHE: /home/runner/.pub-cache
