name: Publish Package to pub.dev

on:
  workflow_dispatch:
      
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CLOUD_KEY }}
        
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        project_id: ${{ secrets.GCLOUD_PROJECT }}

    - name: Install Flutter SDK
      uses: subosito/flutter-action@v2

    - name: Generate OAuth2 refresh token
      id: generate_refresh_token
      run: |
        REFRESH_TOKEN=$(gcloud auth application-default login --no-launch-browser --format='value(refresh_token)')
        echo "::add-mask::$REFRESH_TOKEN"
        echo "REFRESH_TOKEN=$REFRESH_TOKEN" >> $GITHUB_ENV

    - name: Publish to pub.dev
      env:
        PUB_HOSTED_URL: 'https://pub.dartlang.org'
        PUB_REFRESH_TOKEN: ${{ env.REFRESH_TOKEN }}
      run: |
        dart pub publish --force
