name: Publish to pub.dev

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Publish to pub.dev
        run: |
          echo "//pub.dev:$(PUB_DEV_TOKEN)" > ~/.pub-cache/credentials.json
          dart pub publish --force
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
