name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
           flutter-version: "3.10.0"

      - name: Read Pubspec Version
        id: get_version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}')
          VERSION=${VERSION//\'/} # Remove quotes
          echo "::set-output name=version::$VERSION"

      - name: Read Changelog
        id: get_changelog
        run: |
          VERSION="v${{ steps.get_version.outputs.version }}"
          START_TAG="## $VERSION"
          END_TAG="## v"
          
          # Find the line containing the version
          START_LINE=$(grep -n "$START_TAG" CHANGELOG.md | head -n 1 | cut -d: -f1)
          
          if [[ -z "$START_LINE" ]]; then
             echo "::error::Changelog section for version '$VERSION' not found in CHANGELOG.md"
             exit 1
          fi
          
          END_LINE=$(grep -n "$END_TAG" CHANGELOG.md | grep -A 1 -m 1 "$START_TAG" | tail -n 1 | cut -d: -f1)
          
          if [[ -z "$END_LINE" ]]; then
             END_LINE=$(wc -l < CHANGELOG.md)
          fi
          
          echo "start line is $START_LINE and end line is $END_LINE"
          
          # Extract the lines between start and end
          NOTES=$(sed -n "${START_LINE},${END_LINE}p" CHANGELOG.md | tail -n +2 | tr -d '\r')
          
          # set output to variable
          echo "::set-output name=notes::$NOTES"

      - name: Create Git Tag
        run: |
          git tag "v${{ steps.get_version.outputs.version }}"
          echo "TAG created"

      - name: Push Tag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          force: true

      - name: Create GitHub Release (Optional)
        uses: actions/create-release@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          body: ${{ steps.get_changelog.outputs.notes }}
          draft: false
          prerelease: false
